---

- name: Install the dependencies
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl 
    - gnupg 
    - lsb-release
    - python3-pip

- name: Add an Apt signing key to a specific keyring file
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg 
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Set the stable repository
  shell: echo \
         deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) stable | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update cache
  apt:
    update_cache: yes
    
- name: Install Docker
  apt: 
    name: "{{item}}"
    state: present
  with_items:
  - docker-ce 
  - docker-ce-cli
  - containerd.io

- name: Install docker-py 
  pip:
     name: docker

- name: Add user vagrant to docker group
  user:
     name: "{{item}}"
     groups: docker
     append: yes
  become: yes
  with_items:
  - vagrant
              
- name: Download jenkins repo apt URL
  apt_key: 
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  become: yes

- name: Ensure the repository is present
  apt_repository: 
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
    state: present
  become: yes

             
